// Event details JSON
export const eventDetails = [
  {
    id: 1,
    name: "Coding and Debugging",
    slug: "coding-debugging",
    poster: "/coding.jpg",
    rules: [
      "College ID is required for participation.",
      "Spot and online registrations are available.",
      "Online registration closes on Feb 30th.",
    ],
    prizePool: 5000,
    registrationFee: 50,
    memberSize: 1,
    coordinators: ["Aswin", "Sreyas"],
  },
  {
    id: 2,
    name: "Typing",
    slug: "typing",
    poster: "/typing.jpg",
    rules: [
      "College ID is required for participation.",
      "Teams of 2-4 members allowed.",
      "Online registration closes on Feb 30th.",
    ],
    prizePool: 7000,
    registrationFee: 100,
    memberSize: 1,
    coordinators: ["Vishnu", "Sreelakshmi"],
  },
  {
    id: 3,
    name: "Treasure Hunt",
    slug: "treasure-hunt",
    poster: "/treasurehunt.jpg",
    rules: [
      "College ID is required for participation.",
      "Teams of 3-5 members allowed.",
      "24-hour coding challenge.",
    ],
    prizePool: 5000,
    registrationFee: 100,
    memberSize: 4,
    coordinators: ["Arjun", "Megha"],
  },
  {
    id: 4,
    name: "E Football",
    slug: "e-football",
    poster: "/pes.jpg",
    rules: [
      "College ID is required for participation.",
      "Teams of 3-5 members allowed.",
      "24-hour coding challenge.",
    ],
    prizePool: 5000,
    registrationFee: 50,
    memberSize: 1,
    coordinators: ["Arjun", "Megha"],
  },
  {
    id: 5,
    name: "BGMI",
    slug: "bgmi",
    poster: "/pubg.jpg",
    rules: [
      "College ID is required for participation.",
      "Teams of 3-5 members allowed.",
      "24-hour coding challenge.",
    ],
    prizePool: 1000,
    registrationFee: 50,
    memberSize: 1,
    coordinators: ["Arjun", "Megha"],
  },
  {
    id: 6,
    name: "Technical Quiz",
    slug: "technical-quiz",
    poster: "/quiz.jpg",
    rules: [
      "College ID is required for participation.",
      "Teams of 3-5 members allowed.",
      "24-hour coding challenge.",
    ],
    prizePool: 5000,
    registrationFee: 100,
    memberSize: 4,
    coordinators: ["Arjun", "Megha"],
  },
  // {
  //   id: 7,
  //   name: "Hackathon",
  //   slug: "hackathon",
  //   poster: "/slide3.jpg",
  //   rules: [
  //     "College ID is required for participation.",
  //     "Teams of 3-5 members allowed.",
  //     "24-hour coding challenge.",
  //   ],
  //   prizePool: 5000,
  //   registrationFee: 200,
  //   memberSize: 1,
  //   coordinators: ["Arjun", "Megha"],
  // },
];
